[package]
name = "butteryfly-rs-module"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
bitvec = "1.0.1"
boring = "4.21.2"
bytes = "1.11.1"
godot = { version = "0.5.0", features = ["experimental-threads"] }
quiche = { version = "0.28.0", features = ["boringssl-boring-crate"] }
ring = "0.17.14"


[profile.dev]
debug = "line-tables-only"
lto = "off"

[profile.release]
strip = "debuginfo"
lto = "thin"
codegen-units = 4
