[package]
name = "butteryfly-rs-module"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
bitvec = "1.0.1"
godot = { version = "0.3.5", features = ["experimental-threads"] }

[profile.dev]
debug = "line-tables-only"
lto = "off"

[profile.release]
strip = "debuginfo"
lto = "thin"
codegen-units = 4
