#![warn(clippy::all, clippy::pedantic, clippy::nursery)]

//! Low level networking library for the Godot engine.
//!
//! note: this library is currently for internal use only. it can be used in other projects,
//! but the API is subject to change and is not guaranteed to be stable, and many usercases will be poorly supported
//!
//! Currently, Godot provides two networking APIs:
//! the low-level [`MultiplayerPeer`] API and the high-level [`MultiplayerAPI`] API.
//! while these both offer low level access to send raw packets directly,
//! their high level implementations lack the control necessary to optimise networking.
//! sending raw packets, however, requires that the user implements the entire networking protocol themselves.
//! NetNodes intends to be a middle ground, offering the user bit level control over their data representation,
//! while also being as optimised and convienient as possible by default.
//!
//! features:
//! - zero type overhead by default, encoding and decoding is done symmetrically by a single user defined GDScript function
//! - multiple serialization options for each data type, both lossless and lossy, with various quantization levels
//! - branching type decoding using previously decoded data, allowing unneeded data to skip encoding
//! - reliable, ordered messages for sending and receiving data
//! - independent ordered networking streams
//! - flexible node based networking
//! - secure quic based networking using tls 1.3 PSK
//!
//! upcoming features:
//! - delta encoding, usable by both the type serializer and the user defined GDScript function

mod client;
mod common;
mod messages;
mod net_nodes;
mod networker;
mod serializer;
mod server;

use std::net::IpAddr;
use std::net::SocketAddr;
use std::str::FromStr;

use crate::client::NetNodeClient;
use crate::messages::MessageHandler;
use crate::net_nodes::NetworkedNode;
use crate::server::NetNodeServer;
use bitvec::prelude::*;
use godot::prelude::*;

struct MyExtension;

#[gdextension]
unsafe impl ExtensionLibrary for MyExtension {}

/// Handles networking api access by scripts. Contains an inner client or server that handles the actual networking.
/// this must be registered as an autoload singleton in the project settings in order for NetNodes to work.
/// This is also used by NetworkedNodes and MessageHandlers in the background.
/// the inner client or server must be started before either of them are added to the scene tree.
/// starting a client requires a PSK (pre-shared key) generated by the server.
#[derive(GodotClass)]
#[class(init, base=Node)]
struct NetNodeManager {
    inner: Inner,
    base: Base<Node>,
}

#[derive(Debug, Default)]
enum Inner {
    #[default]
    None,
    Client(NetNodeClient),
    Server(NetNodeServer),
}

#[godot_api]
impl NetNodeManager {
    /// not to be called directly, used by NetworkedNode internally.
    /// registers a NetworkedNode with the inner client or server, allowing it to be synced across the network.
    fn register_node(&mut self, node_ref: Gd<NetworkedNode>, node: &mut NetworkedNode) {
        match self.inner {
            Inner::Server(ref mut server) => {
                server.register_node(node_ref);
            }
            Inner::Client(ref mut client) => {
                client.register_node(node_ref, node);
            }
            Inner::None => {
                godot_warn!("called register_node but no client or server is running");
            }
        }
    }

    /// not to be called directly, used by NetworkedNode internally.
    /// unregisters a NetworkedNode from the inner client or server, preventing it from being synced across the network.
    fn unregister_node(&mut self, node_ref: &Gd<NetworkedNode>) {
        match self.inner {
            Inner::Server(ref mut server) => {
                server.unregister_node(node_ref);
            }
            Inner::Client(ref mut client) => {
                client.unregister_node(node_ref);
            }
            Inner::None => {
                godot_warn!("called unregister_node but no client or server is running");
            }
        }
    }

    /// not to be called directly, used by NetworkedNode internally.
    /// returns the next available object id for use by a NetworkedNode.
    /// this is a server only method.
    fn get_next_object_id(&mut self) -> u16 {
        match self.inner {
            Inner::Server(ref mut server) => server.get_next_object_id(),
            _ => {
                godot_error!("called get_next_object_id but we are not a server");
                0
            }
        }
    }

    /// Gets the next client that has connected to the server, but has not yet been verified.
    /// this is intended to connect the PSK used by this client to a user account on another server.
    /// to use this, you should keep track of the user who received a PSK on the other server,
    /// get the user's PSK from this function, retrieve the account associated with the user from the other server,
    /// and then call `verify_client` with the user's PSK and account.
    /// if you do not need to associate the client with a external account, you can generate a random identifier for the account.
    /// once verify_client is called, the client finishes the connection process and will be processed on the server.
    /// this is a server only method.
    #[func]
    fn get_unverified_client(&mut self) -> PackedByteArray {
        match self.inner {
            Inner::Server(ref mut server) => server
                .get_unverified_client()
                .map_or_else(PackedByteArray::new, |x| x.to_godot().to_packed_array()),
            _ => {
                godot_error!("called get_unverified_client but we are not a server");
                PackedByteArray::new()
            }
        }
    }

    /// associates a client with a user account on the server.
    /// this is intended to connect the PSK used by this client to a user account on another server.
    /// to use this, you should keep track of the user who received a PSK on the other server,
    /// get the user's PSK from get_unverified_client, retrieve the account associated with the user from the other server,
    /// and then call this function with the user's PSK and account.
    /// if you do not need to associate the client with a external account, you can generate a random identifier for the account.
    /// once this function is called, the client finishes the connection process and will be processed on the server.
    /// this is a server only method.
    #[func]
    fn verify_client(&mut self, identifier: PackedByteArray, uuid: PackedByteArray) {
        let Ok(identifier) = identifier.to_vec().try_into() else {
            godot_error!(
                "verify_client(): identifier was not correct size: should be {:?} got {:?}",
                40,
                identifier.len()
            );
            return;
        };

        let Ok(uuid) = uuid.to_vec().try_into() else {
            godot_error!(
                "verify_client(): uuid was not correct size: should be {:?} got {:?}",
                16,
                uuid.len()
            );
            return;
        };

        match self.inner {
            Inner::Server(ref mut server) => {
                server.verify_client(identifier, uuid);
            }
            _ => {
                godot_error!("called verify_client but we are not a server");
            }
        }
    }

    /// starts a client connection to a server using the given PSK and identifier.
    /// the PSK and identifier should be generated by the server, and sent through an out of band channel.
    /// once this function is called, client only and generic networking api methods become available.
    #[func]
    fn start_client(
        &mut self,
        server_ip: String,
        server_port: u16,
        psk_identifier: String,
        psk_key: PackedByteArray,
    ) {
        self.inner = Inner::Client(NetNodeClient::new(
            SocketAddr::new(IpAddr::from_str(&server_ip).unwrap(), server_port),
            psk_identifier,
            psk_key.to_vec(),
        ));
    }

    /// starts a server on the given port. the server will always bind to 0.0.0.0.
    /// once this function is called, server only and generic networking api methods become available.
    #[func]
    fn start_server(&mut self, bind_port: u16) {
        self.inner = Inner::Server(NetNodeServer::new(bind_port));
    }

    /// stops the server or client, disconnecting any connected clients and freeing resources.
    /// this is a 'graceful' stop, the client will inform the server before disconnecting,
    /// and the server will wait for all clients to disconnect before stopping.
    /// to forcibly stop a client or server, call [`kill`] instead.
    #[func]
    fn stop(&mut self) {
        match self.inner {
            Inner::Client(ref mut client) => {
                client.disconnect();
            }
            Inner::Server(_) => {
                todo!(
                    "server does not have graceful stop functionality yet, ensure clients have disconnected then kill the server process"
                )
            }
            Inner::None => {}
        }
    }

    /// immediately stops the server or client, deleting associated resources.
    /// any NetworkedNodes or MessageHandlers will be in a limbo state where they still believe they are registered.
    /// this shouldnt cause any issues.
    #[func]
    fn kill(&mut self) {
        self.inner = Inner::None;
    }

    /// returns an identifier that can be used to connect to the server. is composed of an 8 byte identifier and 32 byte key.
    /// this is a server only method.
    #[func]
    fn get_next_client(&mut self) -> PackedByteArray {
        match self.inner {
            Inner::Server(ref mut server) => match server.get_next_client() {
                Ok(client) => PackedByteArray::from(client),
                Err(e) => {
                    godot_error!("failed to get next client: {:?}", e);
                    PackedByteArray::new()
                }
            },
            _ => {
                godot_error!("called get_next_client() but we are not a server");
                PackedByteArray::new()
            }
        }
    }

    /// returns true if the node is a server, false if it is a client or not connected.
    #[func]
    pub fn is_server(&self) -> bool {
        matches!(self.inner, Inner::Server(_))
    }

    /// returns the number of players currently connected to the server.
    /// this is a server only method.
    #[func]
    fn get_player_count(&self) -> i32 {
        match &self.inner {
            Inner::Server(server) => server.get_player_count() as i32,
            _ => {
                godot_error!("tried to get_player_count but we are not a server");
                0
            }
        }
    }

    fn register_message_handler(&mut self, handler: Gd<MessageHandler>, message_type: u64) {
        match &mut self.inner {
            Inner::Client(client) => client.register_message(handler, message_type),
            Inner::Server(server) => server.register_message(handler, message_type),
            _ => {
                godot_error!(
                    "tried to register_message_handler but no client or server is running"
                );
            }
        }
    }

    fn unregister_message_handler(&mut self, message_type: u64) {
        match &mut self.inner {
            Inner::Client(client) => client.unregister_message(message_type),
            Inner::Server(server) => server.unregister_message(message_type),
            _ => {
                godot_error!(
                    "tried to unregister_message_handler but no client or server is running"
                );
            }
        }
    }

    fn queue_message(&mut self, message: BitVec<u64, Lsb0>, stream: u64) {
        match &mut self.inner {
            Inner::Client(client) => client.queue_message(message, stream),
            Inner::Server(server) => server.queue_message(message, stream),
            _ => {
                godot_warn!("tried to queue_message but no client or server is running");
            }
        }
    }
}

#[godot_api]
impl INode for NetNodeManager {
    fn physics_process(&mut self, _delta: f64) {
        match &mut self.inner {
            Inner::Client(client) => client.physics_process_inner(),
            Inner::Server(server) => server.physics_process_inner(),
            _ => {}
        }
    }
}
