name: Build Rust + Godot

on:
  push:
  pull_request:

env:
  GODOT_VERSION: 4.5.1
  EXPORT_NAME: ButterflyVR
  PROJECT_PATH: .

jobs:
  rust-netnodes:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            rust/butteryfly-rs-module/target
          key: ${{ runner.os }}-cargo-netnodes-debug-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-netnodes-debug-

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build Rust module (debug)
        working-directory: rust/butteryfly-rs-module
        run: cargo build

      - name: Upload Rust artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust-netnodes-${{ matrix.os }}-debug
          path: rust/butteryfly-rs-module/target/debug/*.*

  rust-godotpass:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            rust/godot-pass/target
          key: ${{ runner.os }}-cargo-godotpass-release-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-godotpass-release-

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build Rust module (release)
        working-directory: rust/godot-pass
        run: cargo build --release

      - name: Upload Rust artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust-godotpass-${{ matrix.os }}-release
          path: rust/godot-pass/target/release/*.*

  rust-agones-rs:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            rust/agones-godot-rs/target
          key: ${{ runner.os }}-cargo-agones-godot-rs-debug-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-agones-godot-rs-debug-

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install protobuf
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Rust module (debug)
        working-directory: rust/agones-godot-rs
        run: cargo build

      - name: Upload Rust artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust-agones-godot-rs-${{ matrix.os }}-debug
          path: rust/agones-godot-rs/target/debug/*.*

  godot-linux:
    runs-on: ubuntu-22.04
    needs: [rust-netnodes, rust-godotpass, rust-agones-rs]
    container:
      image: barichello/godot-ci:4.5.1
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Download Linux Rust-netnodes artifact
        uses: actions/download-artifact@v4
        with:
          name: rust-netnodes-ubuntu-latest-debug
          path: rust/butteryfly-rs-module/target/debug
          
      - name: Download Linux Rust-godotpass artifact
        uses: actions/download-artifact@v4
        with:
          name: rust-godotpass-ubuntu-latest-release
          path: rust/godot-pass/target/release

      - name: Download Linux Rust-agones-godot-rs artifact
        uses: actions/download-artifact@v4
        with:
          name: rust-agones-godot-rs-ubuntu-latest-debug
          path: rust/agones-godot-rs/target/debug

      - name: Setup Godot templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Export Linux (debug)
        run: |
          mkdir -p build/linux
          EXPORT_DIR="$(readlink -f build/linux)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-debug "Linux" "$EXPORT_DIR/${EXPORT_NAME}.x86_64"

      - name: Upload Godot Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot-linux-debug
          path: build/linux

  godot-windows:
    runs-on: ubuntu-22.04
    needs: [rust-netnodes, rust-godotpass, rust-agones-rs]
    container:
      image: barichello/godot-ci:4.5.1
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Download Linux Rust-netnodes artifact to silence useless errors
        uses: actions/download-artifact@v4
        with:
          name: rust-netnodes-ubuntu-latest-debug
          path: rust/butteryfly-rs-module/target/debug

      - name: Download Linux Rust-godotpass artifact to silence useless errors
        uses: actions/download-artifact@v4
        with:
          name: rust-godotpass-ubuntu-latest-release
          path: rust/godot-pass/target/release

      - name: Download Linux Rust-agones-godot-rs artifact to silence useless errors
        uses: actions/download-artifact@v4
        with:
          name: rust-agones-godot-rs-ubuntu-latest-debug
          path: rust/agones-godot-rs/target/debug

      - name: Download Windows Rust artifact
        uses: actions/download-artifact@v4
        with:
          name: rust-netnodes-windows-latest-debug
          path: rust/butteryfly-rs-module/target/debug
          
      - name: Download Windows Rust-godotpass artifact
        uses: actions/download-artifact@v4
        with:
          name: rust-godotpass-windows-latest-release
          path: rust/godot-pass/target/release

      - name: Download Windows Rust-agones-godot-rs artifact
        uses: actions/download-artifact@v4
        with:
          name: rust-agones-godot-rs-windows-latest-debug
          path: rust/agones-godot-rs/target/debug

      - name: Setup Godot templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Export Windows (debug)
        run: |
          mkdir -p build/windows
          EXPORT_DIR="$(readlink -f build/windows)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-debug "Windows Desktop" "$EXPORT_DIR/${EXPORT_NAME}.exe"

      - name: Upload Godot Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot-windows-debug
          path: build/windows
