name: Build Rust + Godot

on:
  push:
  pull_request:

env:
  GODOT_VERSION: 4.6.3
  EXPORT_NAME: ButterflyVR
  PROJECT_PATH: .

jobs:
  rust:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout

      - name: Cache cargo
        uses: actions/cache
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            rust/target
          key: ${{ runner.os }}-cargo-debug-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-debug-

      - name: Install Rust
        uses: actions-rs/toolchain
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install protobuf
        uses: arduino/setup-protoc
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Rust module (debug)
        working-directory: rust
        run: cargo build

      - name: Upload Rust artifact
        uses: actions/upload-artifact
        with:
          name: rust-${{ matrix.os }}-debug
          path: rust/target/debug/*.*

  godot:
    runs-on: ubuntu-22.04
    needs: [rust]
    container:
      image: barichello/godot-ci:4.6.3
    steps:
      - uses: actions/checkout
        with:
          lfs: true

      - name: Download Linux Rust artifact
        uses: actions/download-artifact
        with:
          name: rust-ubuntu-latest-debug
          path: rust/target/debug

      - name: Download Windows Rust artifact
        uses: actions/download-artifact
        with:
          name: rust-windows-latest-debug
          path: rust/target/debug

      - name: Setup Godot templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Export Linux (debug)
        run: |
          mkdir -p build/linux
          EXPORT_DIR="$(readlink -f build/linux)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-debug "Linux" "$EXPORT_DIR/${EXPORT_NAME}.x86_64"

      - name: Export Windows (debug)
        run: |
          mkdir -p build/windows
          EXPORT_DIR="$(readlink -f build/windows)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-debug "Windows Desktop" "$EXPORT_DIR/${EXPORT_NAME}.exe"

      - name: Upload Godot Linux artifact
        uses: actions/upload-artifact
        with:
          name: godot-linux-debug
          path: build/linux

      - name: Upload Godot Windows artifact
        uses: actions/upload-artifact
        with:
          name: godot-windows-debug
          path: build/windows
